apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app-psql
  labels:
    app: vote-app-db
  namespace: l-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote-app-db
      name: vote-app-psql
  template:
    metadata:
      labels:
        app: vote-app-db
        name: vote-app-psql
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        envFrom:
          - secretRef:
             name: db-secrets 
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "50Mi"
            cpu: "50m"
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: db-data
          subPath: postgres
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: size
                    operator: In
                    values:
                    - Large-02
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: vote-app-pvc
      # volumes:
      # - name: db-data
      #   emptyDir: {}
