---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-app-db
  name: db
  namespace: l-prod
spec:
  type: ClusterIP
  ports:
  - name: "db-service"
    port: 5432
    targetPort: 5432
  selector:
    app: vote-app-db
  
