---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: vote-app-redis
  namespace: voting-app
spec:
  type: ClusterIP
  selector:
    app: vote-app-redis
  ports:
  - name: "redis-service"
    port: 6379
    targetPort: 6379
