apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app-result
  labels:
    app: vote-app-result
  namespace: l-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app-result
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vote-app-result
    spec:
      containers:
      - name: result
        image: dockersamples/examplevotingapp_result
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
          requests:
            memory: "50Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
          name: result
