apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-app-service
  name: vote-app-service
  namespace: l-prod
spec:
  type: ClusterIP
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
    # nodePort: 31000
  selector:
    app: vote-app-vote
  
