apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote-app-worker
  name: vote-app-worker
  namespace: voting-app
spec:
  selector:
    matchLabels:
      app: vote-app-worker
  template:
    metadata:
      labels:
        app: vote-app-worker
    spec:
      containers:
      - image: leohauschild/vote-app-worker:v1.2.2
        name: worker
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
          requests:
            memory: "70Mi"
            cpu: "70m"
