apiVersion: v1
kind: Service
metadata:
  name: {{ include "vote-app.fullname" . }}-{{ .Values.vote.appName }}
  labels:
    app: {{ include "vote-app.fullname" . }}-{{ .Values.vote.appName }}
spec:
  type: {{ .Values.vote.service.type }}
  ports:
    - port: {{ .Values.vote.service.port }}
      targetPort: {{ .Values.vote.service.targetPort }}
      name: {{ .Values.vote.service.name }}
  selector:
    app: {{ include "vote-app.fullname" . }}-{{ .Values.vote.appName }}