apiVersion: v1
entries:
  vote-app:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2023-07-10T08:28:39.901565478-03:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 12.*
    - condition: redis.enabled
      name: redis
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 17.*
    description: A Helm chart for Kubernetes
    digest: d57dfc55e08c211c65305780044c84a646c1d96e4f697b4982f1b5e6eeebd314
    maintainers:
    - email: leohauschild@outlook.com
      name: leohauschild
    name: vote-app
    type: application
    urls:
    - charts/vote-app/charts/vote-app-1.0.0.tgz
    version: 1.0.0
generated: "2023-07-10T08:28:39.893149737-03:00"
