nameOverride: "vote-app"
fullnameOverride: "vote-app"

postgresql:
  enabled: true
  fullnameOverride: db
  primary.name: db
  auth:
    # Assign a password to the "postgres" admin user. Otherwise, remote access will be blocked for this user
    enablePostgresUser: true
    # Password for the "postgres" admin user. Ignored if auth.existingSecret is provided	
    postgresPassword: "postgres"
    
    # Name of existing secret to use for PostgreSQL credentials. auth.postgresPassword, auth.password, and 
    # auth.replicationPassword will be ignored and picked up from this secret. The secret might also contains the key 
    # ldap-password if LDAP is enabled. ldap.bind_password will be ignored and picked from this secret in this case.
    existingSecret:

redis:
  enabled: true
  architecture: standalone
  fullnameOverride: redis
  auth:
    enabled: false
    sentinel: false
  sentinel:
    masterSet: redis	

### Vote configuration ###  
vote:
  appName: vote

  replicaCount: 1

  image:
    repository: leohauschild/vote-app-vote
    pullPolicy: Always
    tag: "v2.0.0"
  imagePullSecrets: ""

  containerPort: 80
  portName: vote-port

  resources:
    requests:
      memory: 50Mi
      cpu: 50m
    limits:
      memory: 200Mi
      cpu: 200m

  nodeSelector: {}
  tolerations: []
  affinity: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  service:
    type: NodePort
    port: 5000
    targetPort: 80
    nodePort: 31002
    name: vote-app-vote-service


### Result configuration ###
result:
  appName: result

  replicaCount: 1

  image:
    repository: leohauschild/vote-app-result
    pullPolicy: Always
    tag: "latest"
  imagePullSecrets: ""

  containerPort: 80
  portName: vote

  resources:
    requests:
      memory: 50Mi
      cpu: 50m
    limits:
      memory: 200Mi
      cpu: 200m

  nodeSelector: {}
  tolerations: []
  affinity: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  service:
    type: NodePort
    port: 5001
    targetPort: 80
    nodePort: 31001
    name: vote-app-result-service

### worker configuration ###
worker:
  appName: worker

  replicaCount: 1

  image:
    repository: leohauschild/vote-app-worker
    pullPolicy: Always
    tag: "latest"
  imagePullSecrets: ""

  resources:
    requests:
      memory: 70Mi
      cpu: 70m
    limits:
      memory: 200Mi
      cpu: 200m

  nodeSelector: {}
  tolerations: []
  affinity: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80