name: Docker Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'


jobs:

  call-docker-build:

    name: Call Docker Build

    uses: ./.github/workflows/reusable-docker-build.yaml

    permissions:
      contents: read
      packages: write
      pull-requests: write
    
    secrets:

      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}

      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

    with:
      
      dockerhub-enable: false
      ghcr-enable: true

      image-name: |
        leohauschild/vote-app-result