name: Docker Build

on:
  push:
    # branches:
    #   - main
    paths:
      - "result/**"
      - "vote/**"
      - "worker/**"
 
  pull_request:
    paths: 
      - "result/**"
      - "vote/**"
      - "worker/**"

jobs:

  call-docker-build:
    name: Call Docker Build
    uses: ./.github/workflows/reusable-docker-test.yaml

    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
    
    secrets:
      dockerhub-username: ${{ secrets.DOCKER_HUB_USER }}  
      dockerhub-token: ${{ secrets.DOCKER_HUB_PASS }}

    with:
      dockerhub-enable: true
      docker-repo: votingapp
