# name: docker-build-worker.yaml

# on:
#   push:
#     # branches:
#     #   - main
#     tags: [ v* ]

#     paths:
#       - "worker/**"
#       - ".github/workflows/docker-build-worker.yaml"

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     outputs: 
#       latest_tag: ${{ steps.get_tag.outputs.latest_tag }}
#     steps:
#       -
#         name: Checkout
#         uses: actions/checkout@v3
#       -  
#         name: Get latest repo tag
#         id: get_tag
#         run: echo "latest_tag=$(git describe --abbrev=0 --tags)" >> "$GITHUB_OUTPUT"
#       -
#         name: Docker meta
#         id: meta
#         uses: docker/metadata-action@v4
#         with:
#           images: leohauschild/vote-app-worker
#           tags: |
#             latest
#             ${{ steps.get_tag.outputs.latest_tag }}
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       -
#         name: Login to Docker Hub
#         if: github.event_name != 'pull_request'
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_HUB_USER }}
#           password: ${{ secrets.DOCKER_HUB_PASS }}
#       -
#         name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           context: worker
#           push: ${{ github.event_name != 'pull_request' }}
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}

#   change-image:
#     needs: [docker]
#     runs-on: ubuntu-latest
#     steps:
#       - 
#         name: checkout
#         uses: actions/checkout@v3
#         with:
#           repository: 'leohauschild/devops_project'
#           token: ${{ secrets.EXTERNAL_REPOSITORY_PERSONAL_ACCESS_TOKEN }}
#       - 
#         name: change image from gitops
#         run: |
#           ls voting-app-yaml-files\/worker_deployment.yaml | xargs sed -i -r "s/image: (.*)/image: leohauschild\/vote-app-worker:${{ needs.docker.outputs.latest_tag }}/g"
#       - 
#         name: commit
#         run: |
#           git config --global user.name leohauschild
#           git config --global user.mail leohauschild@outlook.com
#           git add .
#           git commit -m "change vote-app-worker image tag to ${{ needs.docker.outputs.latest_tag }}"
#           git push origin main